export const DomainTypes = {
  FILTER_NAME: "FILTER_NAME",
  FILTER_CATEGORY: "FILTER_CATEGORY",
  RESET_SEARCHED: "RESET_SEARCHED",
  ADD_TO_CART: "ADD_TO_CART",
  CLEAR_ALL_FROM_CARD: "CLEAR_ALL_FROM_CARD",
  CLEAR_CART: "CLEAR_CART",
  REMOVE_ONE_FROM_CARD: "REMOVE_ONE_FROM_CARD",
};
