export const DomainTypes = {
  FILTER_NAME: "FILTER_NAME",
  FILTER_CATEGORY: "FILTER_CATEGORY",
  RESET_SEARCHED: "RESET_SEARCHED",
  //CLEAR_ALL_FROM_CARD: "CLEAR_ALL_FROM_CARD",
  //CLEAR_CART: "CLEAR_CART",
};
